# Setup
title:               kunanamna
tagline:             'timiza ndoto'
description:         'theme that places the utmost gravity on content with a hidden drawer.'
url:                 https://www.kunanamna.com/
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:             guchi
  url:              
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
